### ISSUE TITLE
I cannot find "domain2actions"

### ISSUE THREAD

**Issue by xhnnn** [sunnweiwei/user-satisfaction-simulation#1]
在 load_jdcc函数中有下面的语句： 
from project.shared_private.jddc_action import domain2actions， 但是project中没有其定义。可以提供一下相关代码吗？

**Comment by sunnweiwei** [comment]
我把domain2action放在了jddc_config里面，修复了一些引用问题。

xhnnn ***@***.***> 于2022年1月10日周一 15:49写道：
